version: 2.1
jobs:
  "Pylint":
    docker:
      - image: cimg/python:3.6.12
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run:
          command: pylint --load-plugins pylint_django --rcfile=.pylintrc zerocater
          no_output_timeout: 20m

  "PEP-8":
    docker:
      - image: cimg/python:3.6.12
    steps:
      - checkout
      - run: pycodestyle --max-line-length=120

workflows:
  version: 2
  build_lint_and_test:
    jobs:
      - "Pylint"
      - "PEP-8"
