FROM python:3
ENV PYTHONUNBUFFERED 1
RUN apt update
RUN apt install entr --yes
RUN mkdir /code
WORKDIR /code
ADD . /code/
RUN pip install -r requirements-dev.txt
# Remove django becaues celery checks if django is installed
RUN pip uninstall --yes django
